targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/gen/{{}}.g.dart'
      json_serializable:
        options:
          include_if_null: false
      freezed:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/gen/{{}}.freezed.dart'
