name: places
description: Sightseeing Guide

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  drift: ^1.6.0
  elementary: ^1.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.1
  geolocator: ^8.2.1
  http_parser: ^4.0.0
  image_picker: ^0.8.5
  json_annotation: ^4.5.0
  latlong2: ^0.8.1
  map_launcher: ^2.2.2
  path: ^1.8.0
  path_provider: ^2.0.9
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  sqlite3_flutter_libs: ^0.5.6
  url_launcher: ^6.1.0
dependency_overrides:
  js: 0.6.4

dev_dependencies:
  build_runner: ^2.1.10
  dart_code_metrics: ^4.15.0
  drift_dev: ^1.6.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  http_mock_adapter: ^0.3.2
  json_serializable: ^6.2.0
  source_gen: ^1.2.2
  surf_lint_rules: ^1.5.0

flutter:
  assets:
    - res/icons/empty_pages/
    - res/icons/menu/
    - res/icons/others/
    - res/icons/catalog/
    - res/icons/tutorial/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: res/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: res/fonts/Roboto-Light.ttf
          weight: 300
        - asset: res/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic

        - asset: res/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: res/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic

        - asset: res/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: res/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: res/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: res/fonts/Roboto-Black.ttf
          weight: 900
        - asset: res/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

  uses-material-design: true

flutter_icons:
  android: launcher_icon
  image_path: res/app_icon/dev/static.png
  adaptive_icon_background: res/app_icon/dev/adaptive_background.png
  adaptive_icon_foreground: res/app_icon/dev/adaptive_foreground.png
  ios: true
  remove_alpha_ios: true