name: places
description: Sightseeing Guide

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.1

dev_dependencies:
  dart_code_metrics: ^4.9.1
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.4.1

flutter:

  uses-material-design: true

  assets:
    - res/fonts/
